CONFIG_ZMK_KEYBOARD_NAME="Viktor's Corne"

# Limit to 2+1 connected devices
CONFIG_BT_MAX_CONN=3
CONFIG_BT_MAX_PAIRED=3

# Future defaults improving connection stability
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Sleep after 10min of inactivity to save the battery (10×60×1000ms)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000

# Reporting battery levels for both halves
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
